qrmenu/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
	#path('login/', views.user_login, name='login'),
	path('login/', auth_views.LoginView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('', views.dashboard, name='dashboard'),
	path('table/', views.meals_table, name='meal_table'),
	path('table/add', views.add_meal, name='add_meal'),
	path('table/update/<int:pk>', views.update, name='update'),
	path('table/delete/<int:pk>', views.delete, name='delete'),	
]

qrmenu/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:meal_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:meal_id>/', views.cart_remove, name='cart_remove'),
]

qrmenu/qrmenu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls')),
    path('', include('restaurant.urls', namespace='restaurant')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

qrmenu/restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'

urlpatterns = [
	path('', views.index, name='index'),
	path('<slug:restaurant_slug>/', views.category_list, name='category_list'),
	path('<slug:restaurant_slug>/<slug:category_slug>/', views.meal_list, name='meals_list_by_category'),
]

qrmenu/account/models.py
from django.db import models

# Create your models here.

qrmenu/cart/models.py
from django.db import models

# Create your models here.

qrmenu/restaurant/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Restaurant(models.Model):
	owner = models.OneToOneField(settings.AUTH_USER_MODEL, related_name="restaurant", on_delete=models.CASCADE)
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, unique=True)
	logo = models.ImageField(upload_to='logos/', blank=True)


	def __str__(self):
		return str(self.name)

class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, unique=True)
	logo = models.ImageField(upload_to='categories/', blank=True)

	class Meta:
		verbose_name_plural = 'categories'

	def __str__(self):
		return str(self.name)

class Meal(models.Model):
	restaurant = models.ForeignKey(Restaurant, related_name='meals', on_delete=models.CASCADE, db_index=True)
	category = models.ForeignKey(Category, related_name='meals', on_delete=models.CASCADE, db_index=True)
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	price = models.DecimalField(max_digits=10, decimal_places=0)
	overview = models.TextField(blank=True)
	def get_file_path(self):
		return 'meals/%r'%(self.restaurant.name)
	image = models.ImageField(upload_to='', blank=True)
	available = models.BooleanField(default=True)

	def __str__(self):
		return str(self.name)

qrmenu/account/forms.py
from django import forms
from restaurant.models import Meal

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

class MealAddForm(forms.ModelForm):
	class Meta:
		model = Meal
		exclude = ['restaurant',]

qrmenu/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

qrmenu/account/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from  .forms import LoginForm, MealAddForm
from django.contrib.auth.decorators import login_required
from restaurant.models import Restaurant, Category, Meal

# Create your views here.
def user_login(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(request, username=cd['username'], password=cd['password'])
			if user is not None:
				if user.is_active:
					login(request, user)
					return HttpResponse('Authenticated successfully')
				else:
					return HttpResponse('Disabled account')
			else:
				return HttpResponse('Invalid login')
	else:
		form = LoginForm
	return render(request, 'account/login.html', {'form':form})

@login_required
def dashboard(request):
	restaurant = get_object_or_404(Restaurant, owner=request.user)
	return render(request, 'account/dashboard.html', {'section':'dashboard', 'restaurant':restaurant})
	
@login_required
def meals_table(request):
	restaurant = get_object_or_404(Restaurant, owner=request.user)
	meals = Meal.objects.filter(restaurant=restaurant)
	return render(request, 'administrator/list.html', {'meals': meals})

@login_required
def add_meal(request):
	restaurant = get_object_or_404(Restaurant, owner=request.user)
	if request.method == 'POST':
		form = MealAddForm(request.POST, files=request.FILES)
		form.instance.restaurant = restaurant
		if form.is_valid():
			form.save()
			return redirect('meal_table')
		else:
			form = MealAddForm()
	else:
		form = MealAddForm()

	return render(request, 'administrator/list.html', {'form': form})

@login_required
def update(request, pk):
	meal = get_object_or_404(Meal, id=pk)
	form = MealAddForm(instance=meal)
	if request.method=="POST":
		form = MealAddForm(request.POST, instance=meal)
		if form.is_valid():
			form.save()
			return redirect('meal_table')
	return render(request, 'administrator/list.html', {'form': form})

@login_required
def delete(request, pk):
	meal = get_object_or_404(Meal, id=pk)
	if request.method=="POST":
		meal.delete()
		return redirect('meal_table')

	return render(request, 'administrator/delete.html', {'meal':meal})

qrmenu/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from restaurant.models import Meal
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, meal_id):
	cart = Cart(request)
	meal = get_object_or_404(Meal, id=meal_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(meal=meal, quantity=cd['quantity'], override_quantity=cd['override'])
	return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, meal_id):
	cart = Cart(request)
	meal = get_object_or_404(Meal, id=meal_id)
	cart.remove(meal)
	return redirect('cart:cart_detail')

def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
	return render(request, 'cart/detail.html', {'cart': cart})

qrmenu/restaurant/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Restaurant, Category, Meal
from django.contrib.auth.decorators import login_required
from cart.forms import CartAddProductForm

# Create your views here.

def index(request):
	restaurants = Restaurant.objects.all()

	return render(request, 'index.html', {'restaurants': restaurants})


def meal_list(request, restaurant_slug, category_slug=None):
	category = None
	restaurant = get_object_or_404(Restaurant, slug=restaurant_slug)
	meals = Meal.objects.filter(restaurant=restaurant)
	categories = set(list(Category.objects.filter(meals__restaurant=restaurant)))
	cart_product_form = CartAddProductForm()
	if category_slug:
		category = Category.objects.get(slug=category_slug)
		meals = meals.filter(category=category)
	return render(request, 'meal/list.html', {'meals': meals, 'categories': categories, 'restaurant': restaurant, 'category': category, 'cart_product_form': cart_product_form})

def category_list(request, restaurant_slug):
	restaurant = get_object_or_404(Restaurant, slug=restaurant_slug)
	meals = Meal.objects.filter(restaurant=restaurant)
	categories = set(list(Category.objects.filter(meals__restaurant=restaurant)))

	return render(request, 'meal/category_list.html', {'restaurant': restaurant, 'categories': categories})

qrmenu/account/templates/administrator/delete.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{meal.name}}"?</p>

			<form action="{% url 'delete' meal.id %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'meal_table' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm" value="Yes">
			</form>
		</div>
	</div>
</div>

{% endblock %}

qrmenu/account/templates/administrator/list.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
		<br>
		<table class="table table-hover">
			<thead>
   				<tr>
      				<th scope="col">#</th>
      				<th scope="col">Name</th>
      				<th scope="col">Category</th>
     				<th scope="col">Price</th>

    			</tr>
  			</thead>
  			<tbody>
  				{% for meal in meals %}
    			<tr>
	      			<th scope="row">{{ forloop.counter }}</th>
    	  			<td>{{ meal.name }}</td>
      				<td>{{ meal.category }}</td>
      				<td>{{ meal.price }} UZS</td>
      				<td><a href="{% url 'update' meal.id %}">Update</a></td>
      				<td><a href="{% url 'delete' meal.id %}">Delete</a></td>
    			</tr>
    			{% endfor %}
  			</tbody>
		</table>
	</div>
	<form action="" method="post" enctype="multipart/form-data">
		{{ form.as_p }}
		{% csrf_token %}
		<input type="submit" value="Submit" class="btn btn-success">
	</form>

{% endblock %}

qrmenu/account/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{% block title %}QR-Menu{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    

    <!-- Bootstrap core CSS -->
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  
<body>
  {% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Eighth navbar example">
    <div class="container">
      <a class="navbar-brand" href="#">QR MENU</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample07">
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'meal_table' %}">Table</a>
          </li>
           <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
          </li>

         
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown07" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown07">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        {% endif %}
      </div>
    </div>
  </nav>
  {% endblock %}

<main>

  {% block content %}{% endblock %}

</main>

    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

      
  </body>
</html>

qrmenu/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Izbrannie
{% endblock %}

{% block content %}
<h1>Cart</h1>
<div class="container">
<table class="table table-image ">
	<thead>
		<tr>
			<th scope="col">Image</th>
			<th scope="col">Product</th>
			<th scope="col">Quantity</th>
			<th scope="col">Remove</th>
			<th scope="col">Unit Price</th>
			<th scope="col">Price</th>
		</tr>
	</thead>
	<tbody>
	{% for item in cart %}
	{% with meal=item.meal %}
	<tr>
		<td class="w-25"><a href="#"><img src="{% if meal.image %}{{ meal.image.url }}{% else %}{% static 'img/no_img.png' %}{% endif %}" class="img-fluid img-thumbnail" alt=""></a>
		</td>
		<td>{{ meal.name }}</td>
		<td>
			<form action="{% url 'cart:cart_add' meal.id %}" method="post">
				{{ item.update_quantity_form.quantity }}
				{{ item.update_quantity_form.override }}
				<input type="submit" value="Update">
				{% csrf_token %}
			</form>
		</td>
		<td>
			<form action="{% url 'cart:cart_remove' meal.id %}" method="post">
				<input type="submit" class="button" value="Remove">
				{% csrf_token %}
			</form>
		</td>
		<td class="num">{{ item.price }} UZS</td>
		<td class="num">{{ item.total_price }} UZS</td>
	</tr>
	{% endwith %}
	{% endfor %}
	<tr class="total">
		<td>Total</td>
		<td colspan="4"></td>
		<td class="num">{{ cart.get_total_price }}</td>
	</tr>
	</tbody>
</table>
</div>
<p class="tex-right">
	<a href="javascript:history.back()" class="button-light">Continue Shopping</a>
</p>
{% endblock %}

qrmenu/restaurant/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Eighth navbar example">
    <div class="container">
      <a class="navbar-brand" href="{% url 'restaurant:index' %}">
        <img src="{% static 'no_logo.png' %}" alt="" width="40" height="40">
      </a>
      <a class="navbar-brand" href="{% url 'restaurant:index' %}">QR Menu</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample07">
      	<ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Partnership</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">More</a>
          </li>
        </ul>

      </div>
    </div>
</nav>
{% endblock %}

{% block content%}
<div class="container">
	<br>
	<h1>QR MENU</h1>
	<h2>Digital Menu</h2>
</div>

<div class="container marketing">
  <div class="container">
<hr class="featurette-divider">
<div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Lorem ipsum dolor sit amet consectetur, adipisicing, elit. Ipsa, nihil ipsum ratione. Quibusdam ullam, modi, suscipit cupiditate nam vero hic ducimus, aspernatur cum voluptatem dolor obcaecati exercitationem nisi numquam voluptatibus enim eveniet dolores sed, illum praesentium nesciunt officia ab eum velit? Consequatur odit quasi, similique nam expedita vitae. Veritatis, laboriosam.</p>
      </div>
      <div class="col-md-5">
        

      </div>
    </div>

    <hr class="featurette-divider">
    </div>

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->

  <div class="container">
    <h2>Our Partners</h2>
  </div>
<div class="container">
<div class="row">
      <div class="col-lg-4 sm-1">
        <div class="container">
        <img src="{% static 'logos/kfc.png' %}" width="140" height="140"alt="">
        <h2>KFC</h2>
        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
        </div>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <div class="container">
        <img src="{% static 'logos/bellissimo.png' %}" width="140" height="140"alt="">
        <h2>Bellissimo</h2>
        <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
        </div>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <div class="container">
        <img src="{% static 'logos/evos.png' %}" width="140" height="140"alt="">
        <h2>Evos</h2>
        <p>And lastly this, the third column of representative placeholder content.</p>
      </div>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->
    </div>
</div>


{% endblock %}

qrmenu/restaurant/templates/meal/category_list.html
{% extends "base.html" %}
{% load static %}

{% block navbar %}

{% endblock %}

{% block content %}

<div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <img src="{% if restaurant.logo %}{{ restaurant.logo.url }}{% else %}{% static 'no_logo.png' %}{% endif %}" alt="" width="40" height="40">
        <span class="fs-4 align-items-center"><strong>{{ restaurant.name }}</strong></span>
      </a>
    </header>
{% for category in categories %}

    <div class="p-5 mb-4 bg-light rounded-3" style="background-image:url({{ category.logo.url }}); background-repeat: no-repeat; background-size: cover;">
      <div class="container-fluid py-5 text-white">
        <h1 class="display-5 fw-bold"></h1>
        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <a href="{% url 'restaurant:meals_list_by_category' restaurant.slug category.slug %}"><button class="btn btn-primary btn-lg" type="button">{{ category.name }}</button></a>
      </div>
    </div>


{% endfor %}

{% endblock %}




    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>

    <footer class="pt-3 mt-4 text-muted border-top">
      &copy; 2021
    </footer>
  </div>

qrmenu/restaurant/templates/meal/list.html
{% extends "base.html" %}
{% load static %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Eighth navbar example">
    <div class="container">
      <a class="navbar-brand" href="{% url 'restaurant:category_list' restaurant.slug %}">
        <img src="{% if restaurant.logo %}{{ restaurant.logo.url }}{% else %}{% static 'no_logo.png' %}{% endif %}" alt="" width="40" height="40">
      </a>
      <a class="navbar-brand" href="{% url 'restaurant:category_list' restaurant.slug %}">{{ restaurant.name }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample07">

          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% for c in categories %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'restaurant:meals_list_by_category' restaurant.slug c.slug %}">{{ c.name }}</a>
          </li>
          {% endfor %}

        </ul>
      </div>
    </div>
</nav>
<nav class="navbar navbar-expand-lg navbar-light bg-light" aria-label="Eighth navbar example">
  <div class="container">
    <h3>Your Cart</h3>
    {% with total_items=cart|length %}
    {% if total_items > 0 %}
    Your cart:
    <a href="{% url 'cart:cart_detail' %}">
      {{ total_items }} items{{ total_items|pluralize }}, {{ cart.get_total_price }} UZS
    </a>
    {% else %}
    Your cart is empty.
    {% endif %}
    {% endwith %}
  </div>
</nav>
{% endblock %}


{% block content %}


<div class="album py-5 bg-light">
    <div class="container">

      {% if category %}
     <h1>{{ category.name }}</h1>
      {% endif %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-4">
        {% for meal in meals %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% if meal.image %}{{ meal.image.url }}{%else %}{% static "img/no_img.png" %}{% endif %}" alt="" class="bd-placeholder-img card-img-top">
            <div class="card-body">
              <h6><strong>{{ meal.name }}</strong></h6>
              <p class="card-text">{% if meal.overview %}{{ meal.overview }}{% endif %}</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text">{{ meal.price }} UZS</small>
              </div>
              <form action="{% url 'cart:cart_add' meal.id %}" method="post" class="post-form">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Add to cart" class="btn btn-primary">
              </form>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>



{% endblock %}